sonar.projectKey=securetask-project
sonar.projectName=securetask-project
sonar.sources=.

# Exclude unwanted build, cache, and report folders from being scanned as code
sonar.exclusions=reports/**/*, venv/**/*, __pycache__/**/*, .sonar/**/*

# Import your Bandit JSON report into SonarQube
sonar.python.bandit.reportPaths=reports/bandit-report.json